project_id = "dxisnnjsbuuiunjmzzqj"

[functions.request-password-reset]
verify_jwt = false

[functions.create-global-user]
verify_jwt = false

[functions.create-system-owners]
verify_jwt = false

[functions.create-tenant-and-owner]
verify_jwt = true

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.invite-user-enhanced]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = true

[functions.send-temp-password]
verify_jwt = false

[functions.send-reservation-email]
verify_jwt = false

[functions.invite-user]
verify_jwt = true

[functions.impersonate-user]
verify_jwt = true

[functions.stop-impersonation]
verify_jwt = true

[functions.suspend-user]
verify_jwt = true

[functions.trial-signup]
verify_jwt = false

[functions.qr-guest-portal]
verify_jwt = false

[functions.qr-staff-portal]
verify_jwt = true

[functions.test-email-provider]
verify_jwt = true

[functions.test-email-provider-simple]
verify_jwt = false

[functions.fix-email-providers]
verify_jwt = true

[functions.emergency-access-verify]
verify_jwt = false

[functions.emergency-access-reset-password]
verify_jwt = false

[functions.reset-system-owner-passwords]
verify_jwt = false

[functions.test-create-user]
verify_jwt = false

[functions.simple-test]
verify_jwt = false

[functions.auto-expire-reservations]

[functions.termii-sms]
verify_jwt = false

[functions.hotel-booking-api]
verify_jwt = false

[functions.africastalking-sms]
verify_jwt = false

[functions.twilio-sms]
verify_jwt = false

[functions.sms-router]
verify_jwt = false

[functions.sms-template-processor]
verify_jwt = false

[functions.qr-unified-api]
verify_jwt = false

[functions.notification-escalation]
verify_jwt = false