project_id = "dxisnnjsbuuiunjmzzqj"

[functions.create-global-user]
verify_jwt = true

[functions.create-tenant-and-owner]
verify_jwt = true

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.paystack-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-temp-password]
verify_jwt = false

[functions.invite-user]
verify_jwt = true

[functions.impersonate-user]
verify_jwt = true

[functions.stop-impersonation]
verify_jwt = true

[functions.suspend-user]
verify_jwt = true

[functions.trial-signup]
verify_jwt = false