project_id = "dxisnnjsbuuiunjmzzqj"

[functions.create-user]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-temp-password]
verify_jwt = false

[functions.create-tenant-and-owner]
verify_jwt = false