// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwamveqcwccpaiwrzifk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3YW12ZXFjd2NjcGFpd3J6aWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MjQ0NjMsImV4cCI6MjA3MTUwMDQ2M30.TV7M5pXhvDEQ_-Zn5Qp1zLqP2R9zYIx2XqvoInLpPmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});